baseURL = 'https://thedubiousmonk.net/'
languageCode = 'en-ca'
title = 'the dubious monk'
theme = 'paperesque'
titleCaseStyle = 'none'

[[params.menu]]
  name = "blog"
  url = "posts/"

[[params.menu]]
  name = "categories"
  url = "categories/"

[[params.menu]]
  name = "tags"
  url = "tags/"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.topmenu]]
  name = "about"
  url = "about/"

[[params.topmenu]]
  name = "rss"
  url = "posts/index.xml"