baseURL = 'https://thedubiousmonk.net/'
languageCode = 'en-ca'
title = 'the dubious monk'
theme = 'paperesque'
titleCaseStyle = 'none'

[[params.topmenu]]
  name = "about"
  url = "about/"

[[params.topmenu]]
  name = "bike"
  url = "categories/cycling/"

[[params.topmenu]]
  name = "rss"
  url = "posts/index.xml"
