baseURL = 'https://thedubiousmonk.net/'
languageCode = 'en-ca'
title = 'the dubious monk'
theme = 'paperesque'

[[params.menu]]
  name = "blog"
  url = "posts/"

[[params.menu]]
  name = "tags"
  url = "tags/"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "contact"
  url = "contact/"