baseURL = 'https://thedubiousmonk.net/'
languageCode = 'en-ca'
title = 'the dubious monk'
theme = 'hugo-book'
titleCaseStyle = 'none'

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

[[params.topmenu]]
  name = "about"
  url = "about/"

[[params.topmenu]]
  name = "bike"
  url = "categories/cycling/"

[[params.topmenu]]
  name = "rss"
  url = "posts/index.xml"

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = true

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  # BookLogo = 'logo.png'

  # (Optional, default 'favicon.png') Set the path to a favicon for the site.
  # If the favicon is in /static/custom.svg, then the path would be 'custom.svg'.
  # BookFavicon = 'favicon.png'

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = 'posts'

  # (Optional, default none) Set template for commit link for the page. Requires enableGitInfo.
  # When set enabled 'Last Modified' and a link to the commit in the footer of the page.
  # Param is executed as template using .Site, .Page and .GitInfo as context.
  BookLastChangeLink = 'https://github.com/alex-shpak/hugo-book/commit/{{ .GitInfo.Hash }}'

  # (Optional, default none) Set template for edit page link.
  # When set enabled 'Edit this page' link in the footer of the page.
  # Param is executed as template using .Site, .Page and .Path as context.
  # BookEditLink = 'https://github.com/alex-shpak/hugo-book/edit/main/exampleSite/{{ .Path }}'

  # (Optional, default 'January 2, 2006') Configure the date format used on the pages
  # - In git information
  # - In blog posts
  # https://gohugo.io/functions/time/format/
  BookDateFormat = 'January 2, 2006'